#!/usr/bin/env node
/**
 * Writes prisma/schema.local.prisma from prisma/schema.prisma, with the
 * datasource provider swapped to sqlite.
 *
 * Why this exists: the repo deploys to Postgres, so schema.prisma says
 * `postgresql`, but local development runs on `file:./dev.db` through
 * @prisma/adapter-libsql. Prisma refuses that pairing outright —
 *
 *   The Driver Adapter `@prisma/adapter-libsql`, based on `sqlite`, is not
 *   compatible with the provider `postgres` specified in the Prisma schema.
 *
 * — so the client used locally has to be generated from a sqlite-provider
 * schema. That used to be a hand-copied schema.prisma.sqlite.bak, which is a
 * trap: any model added to the real schema was missing from the copy, and the
 * failure only showed up as the error above, minutes later and nowhere near the
 * edit. Deriving it means there is exactly one schema to edit.
 *
 * Generated, not committed. Run by `npm run dev`.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const prismaDir = join(dirname(fileURLToPath(import.meta.url)), "..", "prisma");
const source = join(prismaDir, "schema.prisma");
const target = join(prismaDir, "schema.local.prisma");

const schema = readFileSync(source, "utf8");

// Only inside the datasource block: `provider` also names the client generator
// and the driver adapters, and rewriting those would break the output path.
const datasource = /datasource\s+\w+\s*\{[\s\S]*?\}/;
const block = schema.match(datasource);
if (!block) {
    console.error("  ✗ no datasource block in prisma/schema.prisma");
    process.exit(1);
}

const swapped = block[0].replace(/provider\s*=\s*"(postgresql|postgres)"/, 'provider = "sqlite"');
if (swapped === block[0] && !/provider\s*=\s*"sqlite"/.test(block[0])) {
    console.error("  ✗ datasource provider is neither postgresql nor sqlite — nothing to swap");
    process.exit(1);
}

writeFileSync(
    target,
    [
        "// GENERATED by scripts/local-schema.mjs — do not edit.",
        "// Edit prisma/schema.prisma instead; this is that file with the",
        "// datasource provider swapped to sqlite for local development.",
        "",
        schema.replace(datasource, swapped),
    ].join("\n"),
);

console.log("  ✓ prisma/schema.local.prisma written (sqlite) from schema.prisma");
